import { Geist, Geist_Mono } from "next/font/google";
// import Navbar from "@/components/Navbar";
// import Foot from "@/components/foot";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AdminComments-Facebook",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
   <>
   <span>
    Comments Layout
   </span>
   {children}
   
   </>
      
  );
}
